# Numpy

In [1]:
import numpy as np

In [2]:
l = [2, 6, 6, 9]

In [3]:
ln = np.array(l)

In [4]:
l > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [5]:
ln > 2

array([False,  True,  True,  True])

In [6]:
ln * 4

array([ 8, 24, 24, 36])

In [7]:
l * 4

[2, 6, 6, 9, 2, 6, 6, 9, 2, 6, 6, 9, 2, 6, 6, 9]

In [9]:
list(filter(lambda x: x % 2 == 0, ln))

[2, 6, 6]

In [10]:
list(filter(lambda x: x % 2 == 0, l))

[2, 6, 6]

In [12]:
list(map(lambda x: x * 4, l))

[8, 24, 24, 36]

In [14]:
np.where(ln > 3, 'uno', 'dos')

array(['dos', 'uno', 'uno', 'uno'], dtype='<U3')

In [19]:
np.where(l > 2, 'uno', 'dos')

TypeError: '>' not supported between instances of 'list' and 'int'

In [40]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [29]:
np.random.rand(3, 2)

array([[0.48430083, 0.50300815],
       [0.85272907, 0.59529569],
       [0.22781669, 0.87495671]])

In [46]:
np.random.randint(10)

9

In [48]:
np.random.randint(10, 20)

19

In [49]:
np.random.randint(10, 20, 3)

array([14, 13, 10])

In [51]:
k = np.random.randint(10, 20, (3, 2))

In [59]:
s = str(k)

In [60]:
type(s)

str

In [61]:
f = open('prueba', 'w')# WRITE

In [62]:
f.write(s)

27

In [63]:
f.close()

In [65]:
import pandas as pd

In [67]:
df = pd.DataFrame(k)

In [69]:
df.to_csv('prueba.csv', index=False)

In [ ]:
np